name: Publish packages
on:
  release:
    types: [created]

permissions: read-all

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "16"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
